config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # get 'users/index'
  resources :users, only: [:index, :show]


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :events do
    resources :comments
    resources :favorites, only: :create
  end

  resources :favorites, only: [:destroy] do
    patch 'remove_favorite_event'
  end

  get 'profile', to: 'users#profile', as: 'profile'

  root 'events#index'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :hosted_events, foreign_key: "user_id", class_name: "Event"
  has_many :comments, dependent: :destroy

  has_many :favorites
  has_many :events, through: :favorites

  enum role: [:registered, :vip, :moderator, :admin_event, :visit]
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :lastname, :nickname, :date_of_birth, :is_female])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    profile_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all
  end

  def profile
    # @favorites = User.events
  end

  def show
    # @user = User.find[params[:id]]
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="container">
  <h1>Users#index</h1>

  <ul>
    <% @users.each do |user| %>
      <li><%= link_to user.name, user_path(user) %></li>
    <% end %>
    <% if @users == current_user %>
      <li><%= link_to user.name, profile_path %></li>
    <% end %>

  </ul>

</div>

app/views/users/profile.html.erb
<br>
<div class="text-center">
  <div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-8">
      <div class="row">
        <div class="col-sm-4">
          <img src="https://pipelinepros.org/wp-content/uploads/2017/03/Missing-Headshot-Avatar-200x200.png" alt="..." class="img-thumbnail"><%= current_user.photo %>
        </div>
        <div class="col-sm-8">
          <%= current_user.bio %>
          <h3 class="text-center"><%= current_user.name %> <%= current_user.lastname %></h3>
          <h5 class="text-center">"<%= current_user.nickname %>"</h5>
          <p class="text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eleifend porta porta. Nam vestibulum augue mollis lacus pulvinar, et mollis elit posuere. Suspendisse feugiat mattis elit, eget pharetra quam placerat a. Aenean ut enim sapien. Proin posuere convallis metus a scelerisque. Praesent enim nibh, condimentum ut faucibus vel, pulvinar vitae quam. Donec sit amet blandit tellus, at volutpat mi. Nam blandit lectus odio. Pellentesque ut lacus eu nibh pulvinar rutrum.Donec volutpat tempor sodales.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<br><br>
<hr>

<div class="text-center">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10">
          <div class="accordion" id="accordionExample">
            <div class="card">
              <div class="card">
                <div class="card-header" id="headingThree">
                  <h2 class="mb-0">
                    <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                      MIS EVENTOS
                    </button>
                  </h2>
                </div>
                <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                  <div class="card-body">
                    <table class="table">
                      <th><%= link_to 'Nuevo Event', new_event_path, class:'btn btn-dark' %></th>
                      <%# @user.hosted_events.each do |event| %>
                      <tr>
                        <td><%#= image_tag event.pic, style:'width: 100px; height: auto;' %></td>
                        <td><%#= link_to event.title, event_path(event)%></td>

                        <td><%#= link_to 'Editar', edit_event_path(event), class:'btn btn-success' %></td>
                        <td><%#= link_to 'Eliminar', event_path(event), method: :delete, class:'btn btn-danger' %></td>
                      </tr>
                      <%# end %>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<%#= render 'favorites/favoritelist' %>
<%= link_to "Back", :back %>
<br>

app/views/users/show.html.erb
<br>
<div class="text-center">
  <div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-8">
      <div class="row">
        <div class="col-sm-4">
          <img src="https://pipelinepros.org/wp-content/uploads/2017/03/Missing-Headshot-Avatar-200x200.png" alt="..." class="img-thumbnail"><%= current_user.photo %>
        </div>
        <div class="col-sm-8">
          <%= @user.bio %>
          <h3 class="text-center"><%= @user.name %> <%= @user.lastname %></h3>
          <h5 class="text-center">"<%= @user.nickname %>"</h5>
          <p class="text-justify">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eleifend porta porta. Nam vestibulum augue mollis lacus pulvinar, et mollis elit posuere. Suspendisse feugiat mattis elit, eget pharetra quam placerat a. Aenean ut enim sapien. Proin posuere convallis metus a scelerisque. Praesent enim nibh, condimentum ut faucibus vel, pulvinar vitae quam. Donec sit amet blandit tellus, at volutpat mi. Nam blandit lectus odio. Pellentesque ut lacus eu nibh pulvinar rutrum.Donec volutpat tempor sodales.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<br><br>
<hr>

<div class="text-center">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10">
          <div class="accordion" id="accordionExample">
            <div class="card">
              <div class="card">
                <div class="card-header" id="headingThree">
                  <h2 class="mb-0">
                    <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                      MIS EVENTOS
                    </button>
                  </h2>
                </div>
                <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                  <div class="card-body">
                    <table class="table">
                      <% @user.hosted_events.each do |event| %>
                      <tr>
                        <td><%= image_tag event.pic, style:'width: 100px; height: auto;' %></td>
                        <td><%= link_to event.title, event_path(event)%></td>

                        <td><%= link_to 'Editar', edit_event_path(event), class:'btn btn-success' %></td>
                        <td><%= link_to 'Eliminar', event_path(event), method: :delete, class:'btn btn-danger' %></td>
                      </tr>
                      <% end %>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="text-center">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10">
          <div class="accordion" id="accordionExample">
            <div class="card">
              <div class="card">
                <div class="card-header" id="headingTwo">
                  <h2 class="mb-0">
                    <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                      FAVORITOS
                    </button>
                  </h2>
                </div>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                  <div class="card-body">
                    <table class="table">
                      <% @user.favorites.each do |favorite| %>
                      <tr>
                        <td><%= image_tag favorite.event.pic, style:'width: 100px; height: auto;' %></td>
                        <td><%= link_to favorite.event.title, favorite.event %></td>
                        <td><%= favorite.event.datetime %></td>
                      </tr>
                      <% end %>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



<%#= render 'favorites/favoritelist', favorites: @user.favorites %>
<%= link_to "Back", :back %>
<br>

<style>

.row {
  margin: 0;
}

</style>