config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # get 'users/index'
  resources :users, only: [:index, :show]


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :events do
    resources :comments
    resources :favorites, only: :create
  end

  resources :favorites, only: [:destroy] do
    patch 'remove_favorite_event'
  end

  get 'profile', to: 'users#profile', as: 'profile'

  root 'events#index'
end

app/views/shared/_carousel.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12" style="padding: 0;">
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li id="indicator" data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li id="indicator" data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li id="indicator" data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img src="<%= image_path "banner1.png" %>" class="d-block w-100" alt="...">
            </div>
          <div class="carousel-item">
              <img src="<%= image_path "banner2.jpg" %>" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="<%= image_path "banner3.jpg" %>" class="d-block w-100" alt="...">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>
</div>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<br><br>

<style media="screen">

  #indicator {
    background-color: rgb(225, 17, 255);
  }

  img {
    max-width:100%;
  }

</style>

app/views/shared/_footer.html.erb
<footer>
  <div class="container-fluid bg-dark text-white py-3">
    <div class="container">
      <div class="row">
        <div class="col-md-7">
          <div class="row">
            <div class="col-sm-1">
              <a href="#"><i class="fas fa-address-card text-white" style="font-size: 1.5em;"></i></a>
            </div>
            <div class="col-sm-11">
              <div id="contacto">
                <h5>Contáctanos</h5>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-5 text-right">
          <div class="d-inline-block">
            <div id="red-social"><i class="fab fa-facebook-f"></i></div>
            <div id="red-social"><i class="fab fa-twitter"></i></div>
            <div id="red-social"><i class="fab fa-instagram"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <style media="screen">

    footer {
      position: absolute;
      left:0px;
      bottom:0px;
      width: 100%;
    }

    #red-social {
      margin-left: 1em;
      float: left;
    }

    .fab {
      font-size: 25px;
      width: 40px;
      height: 40px;
      line-height: 40px;
      text-align: center;
      text-decoration: none;
      border-radius: 50%;
      color: white;
    }

    .fab:hover {
      opacity: 0.7;
      cursor: pointer;
    }

    .fa-facebook-f {
      background: #3B5998;
    }

    .fa-twitter {
      background: #55ACEE;
    }

    .fa-instagram {
      background: #125688;
    }

  </style>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%= root_path %>">Stgo Cultural</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-item nav-link active' %>
        <% else %>
          <%= link_to 'Login', new_user_session_path, class: 'nav-item nav-link active' %>
          <%= link_to 'Regístrate', new_user_registration_path, class: 'nav-item nav-link active' %>
        <% end %>
      </div>

      <span class="navbar-text" style="display: inline-block; margin-left: 1em;">

        <%= link_to 'Usuarios', users_path %>

        <% if user_signed_in? %>
          <a href="<%= profile_path %>"><i class="fas fa-user"></i>
            <% if current_user.is_female? %>
              Bienvenida <%= current_user.nickname %>!
            <% else %>
              Bienvenido <%= current_user.nickname %>!
            <% end %>
          </a>
        <% end %>
      </span>
    </div>
    <form class="form-inline" style="display: inline-block; margin-left: 1em; left: 0;">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>

</nav>