config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # get 'users/index'
  resources :users, only: [:index, :show]


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :events do
    resources :comments
    resources :favorites, only: :create
  end

  resources :favorites, only: [:destroy] do
    patch 'remove_favorite_event'
  end

  get 'profile', to: 'users#profile', as: 'profile'

  root 'events#index'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites, dependent: :destroy
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @comments = Comment.order('id DESC')
    @comment = Comment.new
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :pic, :flyer, :content, :user_id, :datetime, :latitude, :longitude)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="container">
  <%= form_with(model: event, local: true) do |form| %>
    <% if event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

        <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <%= form.label :pic %>
      <%= form.text_field :pic %>
    </div>

    <div class="field">
      <%= form.label :flyer %>
      <%= form.text_field :flyer %>
    </div>

    <div class="field">
      <%= form.label :content %>
      <%= form.text_area :content %>
    </div>

    <div class="field">
      <%= form.label :datetime %>
      <%= form.datetime_select :datetime %>
    </div>

    <div class="field">
      <%= form.label :latitude %>
      <%= form.text_field :latitude %>
    </div>

    <div class="field">
      <%= form.label :longitude %>
      <%= form.text_field :longitude %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>


</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<%= render 'shared/carousel' %>
<div class="container">
  <div class="text-center">
    <h1 class="glow">En Cartelera</h1>
    <h5><strong>PRÓXIMOS EVENTOS</strong></h5>
  </div><br>

  <div class="row justify-content-md-center">
    <div class="col-md-10">
      <div class="row">
        <% @events.order('id DESC').each do |event| %>
          <div class="col-xs-12 col-sm-6  col-md-6 col-lg-4" style="margin-bottom: 1em;">
            <div class="card">
              <img src="<%= event.pic %>" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title"><%= event.title %></h5>
                <p>Creado por <%= event.user.name %> <%= event.user.lastname %></p>
                <%= link_to 'Ir al Evento', event_path(event), class:'btn btn-dark' %>
                <%= link_to 'Favoritos', event_favorites_path(event), class: "btn btn-primary", method: :post %>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <%= link_to 'New Event', new_event_path %>

    </div>
  </div>

  <br>

</div>

<style>
  h5 {
    color: #e60073;
  }

.glow {
  font-size: 60px;
  color: #fff;
  text-align: center;
  -webkit-animation: glow 1s ease-in-out infinite alternate;
  -moz-animation: glow 1s ease-in-out infinite alternate;
  animation: glow 1s ease-in-out infinite alternate;
}

@-webkit-keyframes glow {
  from {
    text-shadow: 0 0 10px #fff, 0 0 20px #fff, 0 0 30px #e60073, 0 0 40px #e60073, 0 0 50px #e60073, 0 0 60px #e60073, 0 0 70px #e60073;
  }

  to {
    text-shadow: 0 0 20px #fff, 0 0 30px #ff4da6, 0 0 40px #ff4da6, 0 0 50px #ff4da6, 0 0 60px #ff4da6, 0 0 70px #ff4da6, 0 0 80px #ff4da6;
  }
}
</style>

app/views/events/new.html.erb
<div class="container">
  <h1>New Event</h1>

  <%= render 'form', event: @event %>

  <%= link_to 'Back', events_path %>

</div>

app/views/events/show.html.erb
<br><br>
<div class="container text-center">
  <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
      <h3 class="text-center"><%= @event.title %></h3>
      <%= image_tag @event.flyer %>
      <br>
      <p><%= @event.user.nickname %></p>
      <p class="text-left"><%= @event.content %></p>
      <p>
        <strong>Datetime:</strong>
        <%= @event.datetime %>
      </p>
    <!-- <strong>Latitude:</strong>
      <%#= @event.latitude %>
      <strong>Longitude:</strong>
      <%#= @event.longitude %> -->

      <%= form_with(model: [@event, @comment], local: true, class: 'form-horizontal' ) do |f| %>
        <div class="form-group">
          <div class="col-md-8">
            <%= hidden_field_tag :event_id, @event.id %>
            <%= f.text_area :content, placeholder: 'Comenta aquí', class: 'form-control' %>
            <%= f.submit %>
          </div>
        </div>
      <%#= link_to 'Edit', edit_post_comment_path(post),remote: true %>
      <%#= link_to 'delete', post_comment_path(post), method: :delete %>
      <% end %>

      <div class="text-center">
        <div class="row">
          <div class="col-md-2"></div>
          <div class="col-md-8">
            <div class="row">
              <div class="col-sm-1"></div>
              <div class="col-sm-10">
                <div class="accordion" id="accordionExample">
                  <div class="card">
                    <div class="card">
                      <div class="card-header" id="comentar">
                        <h2 class="mb-0">
                          <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                            COMENTARIOS
                          </button>
                        </h2>
                      </div>
                      <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
                        <div class="card-body">
                          <table class="table text-left">
                            <% @comments.each do |comment| %>
                            <tr>
                              <th><%= link_to comment.user.nickname, profile_path %> :</th>
                              <td>
                                <%= comment.content %>
                              </td>
                            </tr>
                            <% end %>
                          </table>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <%= link_to 'Edit', edit_event_path(@event) %> |
      <%= link_to 'Back', events_path %>

    </div>
  </div>
</div>